Repository Mail-0/Zero, pull requests merged in 2025-02, with the labels that each got.

#60 Redesign search and header area
  components/mail/filters.tsx
  components/mail/mail.tsx
Labels: design

#163 feat(legal): update pages UI
  app/(full-width)/privacy/page.tsx
  app/(full-width)/terms/page.tsx
  app/page.tsx
Labels: on hold

#143 fix(contributors): change wording to include prs
  app/(full-width)/contributors/page.tsx
Labels: Low Priority

#142 Fixed some of the ui inconsistencies
  app/(full-width)/contributors/page.tsx
  app/(routes)/mail/page.tsx
  components/mail/mail-display.tsx
  components/mail/mail.tsx
  components/ui/nav-user.tsx
Labels: Low Priority, design

#248 redo: settings back button restore mail folder view for new UI
  components/ui/nav-main.tsx
  config/navigation.ts
Labels: on hold

#285 Fix:React Scan in development mode
  app/layout.tsx
Labels: High Priority

#289 fix: Login Workflow
  components/mail/empty-state.tsx
Labels: High Priority

#306 feat: added filter logic and improved search bar and filtering UI
  components/mail/empty-state.tsx
  components/mail/mail-list.tsx
  components/mail/mail.tsx
  components/mail/search-bar.tsx
  hooks/use-search-value.ts
Labels: enhancement, Medium Priority
