Repository Mail-0/Zero, pull requests merged in 2025-07, with the labels that each got.

#1837 Add user topics generation and label management
  apps/mail/components/party.tsx
  apps/server/package.json
  apps/server/src/lib/analyze/interests.ts
  apps/server/src/lib/brain.fallback.prompts.ts
  apps/server/src/lib/factories/google-subscription.factory.ts
  apps/server/src/pipelines.effect.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/routes/agent/rpc.ts
  apps/server/src/routes/agent/types.ts
  pnpm-lock.yaml
Labels: design, High Priority, content

#1841 fix: auto-focus reply input when reply is triggered
  apps/mail/components/mail/reply-composer.tsx
Labels: design

#1845 Optimize thread synchronization with rate limiting and concurrency control
  apps/server/src/routes/agent/index.ts
  apps/server/src/routes/agent/rpc.ts
Labels: High Priority

#1853 Refactor workflow processing to use durable objects for better concurrency
  apps/server/src/main.ts
  apps/server/src/pipelines.effect.ts
  apps/server/src/pipelines.ts
  apps/server/src/thread-workflow-utils/workflow-engine.ts
  apps/server/src/thread-workflow-utils/workflow-functions.ts
  apps/server/wrangler.jsonc
Labels: design, High Priority

#1855 fix: add draft generation check
  apps/server/src/thread-workflow-utils/index.ts
  apps/server/src/thread-workflow-utils/workflow-engine.ts
  apps/server/src/thread-workflow-utils/workflow-functions.ts
Labels: content

#1573 feat: add email template management functionality
  apps/mail/components/create/email-composer.tsx
  apps/mail/components/create/template-button.tsx
  apps/mail/components/ui/toast.tsx
  apps/mail/hooks/use-templates.ts
  apps/server/src/db/migrations/0035_giant_hydra.sql
  apps/server/src/db/migrations/0036_petite_mole_man.sql
  apps/server/src/db/migrations/meta/0036_snapshot.json
  apps/server/src/db/migrations/meta/_journal.json
  apps/server/src/db/schema.ts
  apps/server/src/lib/templates-manager.ts
  apps/server/src/main.ts
  apps/server/src/trpc/index.ts
  apps/server/src/trpc/routes/templates.ts
Labels: design, High Priority

#1872 Implement workflow chain execution to share results between workflows
  apps/server/src/main.ts
  apps/server/src/pipelines.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/thread-workflow-utils/workflow-engine.ts
Labels: design, High Priority
