Repository Mail-0/Zero, pull requests merged in 2025-08, with the labels that each got.

#1882 HMR fix
  apps/mail/app/root.tsx
Labels: High Priority

#1877 feat: add tests using playwright
  .env.example
  package.json
  packages/testing/e2e/auth.setup.ts
  packages/testing/e2e/mail-inbox.spec.ts
  packages/testing/package.json
  packages/testing/playwright.config.ts
  packages/testing/tsconfig.json
  pnpm-lock.yaml
Labels: High Priority, content

#1873 Integrate Dormroom for durable object management and queryable storage
  apps/mail/app/root.tsx
  apps/mail/providers/query-provider.tsx
  apps/server/package.json
  apps/server/src/env.ts
  apps/server/src/lib/server-utils.ts
  apps/server/src/main.ts
  apps/server/src/pipelines.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/trpc/routes/mail.ts
  apps/server/src/trpc/trpc.ts
  pnpm-lock.yaml
Labels: design, High Priority

#1878 fix: update locale keys for Chinese language support
  apps/mail/locales.ts
Labels: High Priority, content

#1888 Make AutoRAG optional and improve thread summary fallback
  apps/server/src/routes/agent/index.ts
  apps/server/src/routes/agent/tools.ts
  apps/server/src/routes/ai.ts
  scripts/register-elevenlabs-tools.ts
Labels: design, content

#1895 Remove thread ID tracking and filter suggestion files
  apps/mail/components/party.tsx
  apps/mail/lib/filter.ts
  apps/mail/lib/utils.ts
  apps/mail/providers/query-provider.tsx
  apps/server/src/lib/filter.ts
  apps/server/src/lib/utils.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/routes/agent/orchestrator.ts
  apps/server/src/routes/agent/tools.ts
  apps/server/src/routes/agent/types.ts
  apps/server/src/trpc/routes/mail.ts
Labels: design, High Priority

#1896 Add thread context to AI chat and enhance security with locked prompts
  apps/mail/components/create/ai-chat.tsx
  apps/mail/components/ui/prompts-dialog.tsx
  apps/server/src/lib/brain.ts
  apps/server/src/pipelines.effect.ts
  apps/server/src/routes/agent/index.ts
Labels: design, High Priority, content

#1893 Fix toast styling
  apps/mail/components/ui/toast.tsx
  apps/mail/package.json
  pnpm-lock.yaml
Labels: design

#1894 Fix sizes and styles of AI sidebar icons
  apps/mail/app/globals.css
  apps/mail/components/ui/ai-sidebar.tsx
  apps/mail/components/ui/prompts-dialog.tsx
Labels: design

#1898 Remove hardcoded Cloudflare credentials from configuration files
  apps/server/src/env.ts
  apps/server/wrangler.jsonc
Labels: High Priority

#1900 Fix/mail detail box width fix
  apps/mail/components/mail/mail-display.tsx
Labels: design

#1851 Fix: render HTML instead of raw code on print
  apps/mail/components/mail/mail-display.tsx
Labels: design

#1902 Redesign mail categories to use label-based filtering instead of search queries
  .husky/pre-commit
  AGENT.md
  apps/mail/app/(routes)/settings/categories/page.tsx
  apps/mail/app/routes.ts
  apps/mail/components/mail/mail-list.tsx
  apps/mail/components/mail/mail.tsx
  apps/mail/components/settings/settings-card.tsx
  apps/mail/components/ui/nav-main.tsx
  apps/mail/config/navigation.ts
  apps/mail/hooks/use-categories.ts
  apps/mail/lib/hotkeys/mail-list-hotkeys.tsx
  apps/mail/messages/en.json
  apps/server/src/lib/schemas.ts
  apps/server/src/routes/agent/index.ts
  package.json
Labels: design, content

#1915 Add email syncing status indicators and optimize folder synchronization
  apps/mail/components/mail/mail.tsx
  apps/mail/components/mail/use-do-state.ts
  apps/mail/components/party.tsx
  apps/server/src/lib/server-utils.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/routes/agent/types.ts
Labels: design, content

#1917 Refactor ZeroDriver to use SQLite database for thread and label management
  apps/mail/components/mail/mail.tsx
  apps/mail/components/mail/use-do-state.ts
  apps/mail/components/navigation.tsx
  apps/mail/components/party.tsx
  apps/mail/components/ui/nav-user.tsx
  apps/mail/hooks/use-stats.ts
  apps/server/src/lib/server-utils.ts
  apps/server/src/main.ts
  apps/server/src/pipelines.ts
  apps/server/src/routes/agent/db/drizzle.config.ts
  apps/server/src/routes/agent/db/drizzle/0000_tired_radioactive_man.sql
  apps/server/src/routes/agent/db/drizzle/meta/0000_snapshot.json
  apps/server/src/routes/agent/db/drizzle/meta/_journal.json
  apps/server/src/routes/agent/db/drizzle/migrations.js
  apps/server/src/routes/agent/db/index.ts
  apps/server/src/routes/agent/db/schema.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/routes/agent/mcp.ts
  apps/server/src/routes/agent/orchestrator.ts
  apps/server/src/routes/agent/rpc.ts
  apps/server/src/routes/agent/tools.ts
  apps/server/src/routes/agent/types.ts
  apps/server/src/thread-workflow-utils/workflow-functions.ts
  apps/server/src/trpc/routes/drafts.ts
  apps/server/src/trpc/routes/label.ts
  apps/server/src/trpc/routes/mail.ts
  apps/server/wrangler.jsonc
Labels: design, High Priority, content

#1924 Remove sync status indicator and fix JSON trailing commas
  apps/mail/components/mail/mail.tsx
  apps/server/wrangler.jsonc
Labels: design, content

#1931 Add retry mechanism for thread listing failures in syncThreads
  apps/server/src/routes/agent/index.ts
Labels: High Priority

#1934 fix: remove double toast and decrease time from 30s to 15s
  apps/mail/components/create/create-email.tsx
  apps/mail/components/mail/reply-composer.tsx
  apps/mail/hooks/use-undo-send.ts
Labels: design

#1938 fix: hotkeys for categories
  apps/mail/components/mail/mail.tsx
Labels: design

#1937 Add ThreadSyncWorker for improved thread synchronization
  apps/mail/components/mail/mail.tsx
  apps/server/src/env.ts
  apps/server/src/lib/gmail-rate-limit.ts
  apps/server/src/main.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/routes/agent/sync-worker.ts
  apps/server/wrangler.jsonc
Labels: design

#1943 Implement database sharding for improved email storage scalability
  apps/mail/app/(routes)/mail/layout.tsx
  apps/mail/components/mail/mail-display.tsx
  apps/mail/components/mail/use-do-state.ts
  apps/mail/components/party.tsx
  apps/mail/components/ui/ai-sidebar.tsx
  apps/mail/components/ui/nav-user.tsx
  apps/mail/hooks/use-optimistic-actions.ts
  apps/server/src/env.ts
  apps/server/src/lib/server-utils.ts
  apps/server/src/main.ts
  apps/server/src/pipelines.ts
  apps/server/src/routes/agent/db/index.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/routes/agent/mcp.ts
  apps/server/src/routes/agent/tools.ts
  apps/server/src/routes/agent/types.ts
  apps/server/src/thread-workflow-utils/workflow-functions.ts
  apps/server/src/trpc/routes/connections.ts
  apps/server/src/trpc/routes/mail.ts
  apps/server/src/workflows/sync-threads-coordinator-workflow.ts
  apps/server/src/workflows/sync-threads-workflow.ts
  apps/server/wrangler.jsonc
Labels: design

#1940 chore: refine system prompt and small update to eval
  apps/mail/lib/prompts.ts
  apps/server/evals/ai-chat-basic.eval.ts
  apps/server/src/lib/prompts.ts
Labels: High Priority, content

#1923 feat: add playwright tests for bulk actions and search
  apps/mail/components/create/ai-chat.tsx
  packages/testing/e2e/bulk-search.spec.ts
Labels: content

#1922 feat: add tests for optimistic actions
  packages/testing/e2e/mail-actions.spec.ts
Labels: content

#1921 feat: add playwright tests to check search bar functions
  packages/testing/e2e/search-bar.spec.ts
Labels: content

#1948 Enable spam email processing and improve label management workflow
  apps/server/package.json
  apps/server/src/env.ts
  apps/server/src/lib/utils.ts
  apps/server/src/pipelines.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/thread-workflow-utils/workflow-engine.ts
  apps/server/src/thread-workflow-utils/workflow-functions.ts
  apps/server/wrangler.jsonc
  scripts/bun.lock
  scripts/run.ts
Labels: design, content

#1949 Optimize thread counting and add license headers to workflow files
  apps/mail/app/(auth)/login/login-client.tsx
  apps/mail/app/(full-width)/contributors.tsx
  apps/mail/app/(full-width)/privacy.tsx
  apps/mail/app/(full-width)/terms.tsx
  apps/mail/app/(routes)/developer/page.tsx
  apps/mail/app/(routes)/settings/connections/page.tsx
  apps/mail/components/create/editor.tsx
  apps/mail/components/labels/label-dialog.tsx
  apps/mail/components/mail/mail-display.tsx
  apps/mail/components/mail/mail-list.tsx
  apps/mail/components/mail/note-panel.tsx
  apps/mail/components/mail/thread-display.tsx
  apps/mail/components/navigation.tsx
  apps/mail/components/theme/theme-toggle.tsx
  apps/mail/components/ui/accordion.tsx
  apps/mail/components/ui/app-sidebar.tsx
  apps/mail/components/ui/input-otp.tsx
  apps/mail/components/ui/progress.tsx
  apps/mail/components/ui/sidebar.tsx
  apps/mail/components/ui/tabs.tsx
  apps/server/src/env.ts
  apps/server/src/lib/server-utils.ts
  apps/server/src/routes/agent/db/index.ts
  apps/server/src/routes/agent/index.ts
  apps/server/src/thread-workflow-utils/workflow-engine.ts
  apps/server/src/thread-workflow-utils/workflow-functions.ts
  apps/server/src/trpc/index.ts
  apps/server/src/trpc/routes/meet.ts
  apps/server/src/workflows/sync-threads-coordinator-workflow.ts
  apps/server/src/workflows/sync-threads-workflow.ts
  apps/server/wrangler.jsonc
Labels: design, content

#1950 Add rate limiting to meet creation endpoint
  apps/mail/components/ui/app-sidebar.tsx
  apps/mail/hooks/use-billing.ts
  apps/mail/lib/utils.ts
  apps/server/src/ctx.ts
  apps/server/src/lib/auth.ts
  apps/server/src/lib/server-utils.ts
  apps/server/src/lib/utils.ts
  apps/server/src/main.ts
  apps/server/src/routes/autumn.ts
  apps/server/src/trpc/index.ts
  apps/server/src/trpc/routes/meet.ts
Labels: High Priority

#1947 feat: add email right back into the composer once you click undo
  apps/mail/components/create/create-email.tsx
  apps/mail/components/mail/reply-composer.tsx
  apps/mail/hooks/use-undo-send.ts
Labels: design

#1962 Use configurable runner image in GitHub workflows
  .github/workflows/ci.yml
  .github/workflows/close-conflicted-prs.yml
  .github/workflows/close-stale-issues.yml
  .github/workflows/deploy-to-prod-command.yml
  .github/workflows/lingo-dev.yml
  .github/workflows/sync-production.yml
Labels: design

#1942 fix: contact us navigation on mobile view
  apps/mail/components/navigation.tsx
Labels: design

#1905 fix: improve link visibility on logout screen when light theme is sel…
  apps/mail/app/(auth)/login/login-client.tsx
Labels: design

#1903 fix: update locale identifiers for Chinese languages
  apps/mail/locales.ts
  apps/mail/messages/zh_CN.json
  apps/mail/messages/zh_TW.json
  apps/mail/project.inlang/settings.json
  i18n.json
Labels: content

#1856 feat: add range selection support for thread list
  apps/mail/components/mail/mail-list.tsx
Labels: design, High Priority

#1963 Improve auth error handling and connection reset functionality
  apps/server/src/lib/auth.ts
  apps/server/src/lib/server-utils.ts
  apps/server/src/trpc/routes/mail.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: High Priority

#1495 feat: add autosuggestions while sending email
  apps/mail/components/create/email-composer.tsx
  apps/mail/components/ui/recipient-autosuggest.tsx
  apps/server/src/routes/agent/index.ts
  apps/server/src/trpc/routes/mail.ts
Labels: design, High Priority, content

#1974 Add cursor-pointer to CTA buttons and navigation items for better UX
  apps/mail/components/home/footer.tsx
  apps/mail/components/navigation.tsx
Labels: design

#1984 fix: remove primary border from draft list and overflow visible
  apps/mail/components/mail/mail-list.tsx
Labels: design

#1908 Feat: label creation flow fix
  apps/mail/components/context/thread-context.tsx
  apps/mail/components/labels/label-dialog.tsx
  apps/mail/components/ui/nav-main.tsx
Labels: design, content

#1993 fix: show hand cursor on all buttons
  apps/mail/components/ui/button.tsx
Labels: design

#1991 UI: improved back icon for command palette
  apps/mail/components/context/command-palette-context.tsx
Labels: design

#1999 cleanup of ui elements
  apps/mail/components/labels/label-dialog.tsx
  apps/mail/components/ui/button.tsx
  apps/mail/components/ui/nav-user.tsx
Labels: design

#1994 Fix: ensure email text is visible in light mode (issue #1966)
  apps/mail/components/mail/mail-content.tsx
Labels: design

#1990 Datadog Implementation
  apps/mail/lib/trpc.ts
  apps/server/package.json
  apps/server/src/ctx.ts
  apps/server/src/env.ts
  apps/server/src/lib/datadog-service.ts
  apps/server/src/lib/logging-service.ts
  apps/server/src/lib/server-utils.ts
  apps/server/src/lib/trace-context.ts
  apps/server/src/lib/trpc-logging.ts
  apps/server/src/main.ts
  apps/server/src/trpc/index.ts
  apps/server/src/trpc/routes/logging.ts
  apps/server/src/trpc/trpc.ts
  apps/server/src/types/logging.ts
  apps/server/wrangler.jsonc
  pnpm-lock.yaml
Labels: High Priority

#2006 update deps and remove unused deps
  apps/mail/package.json
  apps/server/package.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: High Priority

#2007 Fix: deletion toast Undo button misaligned
  apps/mail/components/ui/toast.tsx
Labels: design

#1983 feat: simplify the date picking usage when a user schedules an email and remove premature "in the past" warning
  apps/mail/components/create/schedule-send-picker.tsx
  apps/mail/components/ui/calendar.tsx
Labels: design, High Priority

#2010 feat: reorganize dropdown menu footer for better UX - Move Toggle The…
  apps/mail/components/ui/nav-user.tsx
Labels: design
